
# Variable names for "Verlustscheine"

oldnames <- c("Krankenkasse",
              "Dossier Nr.",
              "*\r\nName Schuldner",
              "*\r\nVorname...4",
              "*\r\nStrasse",
              "*\r\nNr....6",
              "*\r\nPLZ...7",
              "*\r\nOrt...8",
              "*\r\nName Versicherter",
              "*\r\nVorname...10",
              "*\r\nGeschlecht\r\nM/F",
              "*\r\n Strasse",
              "*\r\nNr....13",
              "*\r\nPLZ...14",
              "*\r\nOrt...15",
              "*\r\nGeburtsdatum",
              "*\r\nNeue AHV-Nr.",
              "Versicherten-Nr.",
              "Interne Betreibungs-Nr. des Versicherers",
              "Verlustschein-Nr.",
              "*\r\nDatum des Verlustscheins\r\n\r\nTT MM JJJJ",
              "*\r\nBetreibungsamt Name, PLZ, Ort",
              "Betreibungsamt Name, PLZ, Ort...23",
              "Betreibungsamt Name, PLZ, Ort...24",
              "vom...25",
              "bis...26",
              "vom...27",
              "bis...28",
              "pro Versicherten...29",
              "pro Versicherten...30",
              "pro Versicherten...31",
              "pro Versicherten...32",
              "pro Schuldner...33",
              "pro Schuldner...34",
              "...35",
              "...36",
              "Andere Zahlungen durch Schuldner",
              "von IPV",
              "Annulation / andere Zahlungen")


newnames <- c("insurance",
              "id_dossier",
              "debtor_surname",
              "debtor_firstname",
              "debtor_street",
              "debtor_street_nr",
              "debtor_plz",
              "debtor_wohnort",
              "surname",
              "firstname",
              "gender",
              "street",
              "street_nr",
              "plz",
              "wohnort",
              "birthday",
              "ahvnr",
              "insured_nr",
              "debt_claim_nr",
              "loss_slip_nr",
              "loss_slip_date",
              "debt_coll_office_name",
              "debt_coll_office_plz",
              "debt_coll_office_place",
              "premium_period_from",
              "premium_period_til",
              "costshare_period_from",
              "costshare_period_til",
              "premium_gross",
              "premium_subsidy",
              "premium",
              "costshare",
              "interest",
              "debt_coll_cost",
              "partial_payments",
              "uncovered",
              "refunds_from_debtor",
              "refunds_from_ipv",
              "refunds_annulation_other")
